<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" ignored="0" name="Test" tests="4" failures="1" timestamp="2020-08-12T20:44:38 IST" time="17.661" errors="0">
  <testcase name="enterEmailForLogin_NegativeTest" time="2.235" classname="flipkart.Test.NegativeTest"/>
  <testcase name="enterPassword_NegativeTest" time="1.376" classname="flipkart.Test.NegativeTest">
    <failure type="java.lang.AssertionError" message="expected [flipk@rt123] but found [flipk@rt4564]">
      <![CDATA[java.lang.AssertionError: expected [flipk@rt123] but found [flipk@rt4564]
at flipkart.Test.NegativeTest.enterPassword_NegativeTest(NegativeTest.java:92)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- enterPassword_NegativeTest -->
  <testcase name="clickOnLogin_NegativeTest" time="2.09" classname="flipkart.Test.NegativeTest"/>
  <testcase name="screenshot_NegativeTest" time="3.397" classname="flipkart.Test.NegativeTest"/>
</testsuite> <!-- Test -->
